"""Criação das features de usuário

Revision ID: e5a4e3556d3a
Revises: 0ca638887012
Create Date: 2021-11-24 18:23:14.327160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5a4e3556d3a'
down_revision = '0ca638887012'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('telephone', sa.String(), nullable=True))
    op.add_column('users', sa.Column('email', sa.String(), nullable=True))
    op.add_column('users', sa.Column('password', sa.String(), nullable=True))
    op.add_column('users', sa.Column('is_provider', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin')
    op.drop_column('users', 'is_provider')
    op.drop_column('users', 'password')
    op.drop_column('users', 'email')
    op.drop_column('users', 'telephone')
    # ### end Alembic commands ###
